"""add_lessons_table_and_update_course_schema

Revision ID: 46643d991d6c
Revises: a0c57abf98b9
Create Date: 2025-09-27 19:57:36.971988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46643d991d6c'
down_revision: Union[str, Sequence[str], None] = 'a0c57abf98b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.add_column('courses', sa.Column('title', sa.String(length=500), nullable=False))
    op.add_column('courses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('learning_objectives', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('courses', sa.Column('source_from', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('courses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('courses', 'name')
    op.add_column('modules', sa.Column('title', sa.String(length=500), nullable=False))
    op.add_column('modules', sa.Column('order_index', sa.Integer(), nullable=False))
    op.add_column('modules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('modules', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('modules', 'updated_at')
    op.drop_column('modules', 'order_index')
    op.drop_column('modules', 'title')
    op.add_column('courses', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('courses', 'updated_at')
    op.drop_column('courses', 'source_from')
    op.drop_column('courses', 'learning_objectives')
    op.drop_column('courses', 'difficulty')
    op.drop_column('courses', 'estimated_duration')
    op.drop_column('courses', 'description')
    op.drop_column('courses', 'title')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
