"""update_guide_source_from_to_array

Revision ID: 7823d843abc7
Revises: 4fd1c352e26a
Create Date: 2025-10-18 15:46:19.668706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7823d843abc7'
down_revision: Union[str, Sequence[str], None] = '4fd1c352e26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Alter source_from column to be an array of strings
    # Use raw SQL to handle the type conversion properly
    op.execute("ALTER TABLE guides ALTER COLUMN source_from TYPE VARCHAR[] USING CASE WHEN source_from IS NULL THEN NULL ELSE ARRAY[source_from] END")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert source_from column back to string
    # Use raw SQL to handle the type conversion properly
    op.execute("ALTER TABLE guides ALTER COLUMN source_from TYPE VARCHAR(500) USING CASE WHEN source_from IS NULL THEN NULL ELSE source_from[1] END")
    # ### end Alembic commands ###
