"""update_course_schema_for_ai_generated_courses

Revision ID: a0c57abf98b9
Revises: 4b5c6d7e8f90
Create Date: 2025-09-27 19:40:43.869186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c57abf98b9'
down_revision: Union[str, Sequence[str], None] = '4b5c6d7e8f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_oauth_tokens_provider', table_name='user_oauth_tokens')
    op.drop_index('ix_user_oauth_tokens_user_id', table_name='user_oauth_tokens')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index('ix_user_oauth_tokens_user_id', 'user_oauth_tokens', ['user_id'], unique=False)
    op.create_index('ix_user_oauth_tokens_provider', 'user_oauth_tokens', ['provider'], unique=False)
    # ### end Alembic commands ###
